/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

/**
 *
 * @author Matheus
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btUsuario = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        btLivro = new javax.swing.JMenu();
        menuLivro = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        btCategoria = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Sistema de Empréstimo de Livro");

        btUsuario.setText("Usuario");

        menuUsuario.setText("Cadastrar");
        menuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuarioMouseClicked(evt);
            }
        });
        btUsuario.add(menuUsuario);

        jMenuBar1.add(btUsuario);

        btLivro.setText("Livro");

        menuLivro.setText("Cadastrar");
        menuLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLivroMouseClicked(evt);
            }
        });
        btLivro.add(menuLivro);

        jMenuBar1.add(btLivro);

        jMenu7.setText("Categoria");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });

        btCategoria.setText("Cadastrar");
        btCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCategoriaMouseClicked(evt);
            }
        });
        jMenu7.add(btCategoria);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("Emprestimo");

        jMenu10.setText("Cadastrar");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu9.add(jMenu10);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked

    }//GEN-LAST:event_jMenu7MouseClicked

    private void btCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCategoriaMouseClicked
        CadastroCategoriaGUI novo = new CadastroCategoriaGUI();
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCategoriaMouseClicked

    private void menuLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLivroMouseClicked
        CadastroLivroGUI novo = new CadastroLivroGUI();
        novo.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menuLivroMouseClicked

    private void menuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuarioMouseClicked
        CadastroUsuarioGUI novo = new CadastroUsuarioGUI();
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuUsuarioMouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        CadastroEmprestimoGUI novo = new CadastroEmprestimoGUI();
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu10MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btCategoria;
    private javax.swing.JMenu btLivro;
    private javax.swing.JMenu btUsuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuLivro;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
